// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKspMUiy_HNuQXZL7lVhX3hb-5046BMew',
    appId: '1:583000002076:web:13972a64e86f0c871f19d9',
    messagingSenderId: '583000002076',
    projectId: 'travel-together-d671c',
    authDomain: 'travel-together-d671c.firebaseapp.com',
    storageBucket: 'travel-together-d671c.firebasestorage.app',
    measurementId: 'G-P2JKPK3BFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdwGcqKYNt5Vm4QddCZc_kq5sc-TyOhi4',
    appId: '1:583000002076:android:9084d8849bf13f271f19d9',
    messagingSenderId: '583000002076',
    projectId: 'travel-together-d671c',
    storageBucket: 'travel-together-d671c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWK9sX_aPTmbg1al-5UpBLRvLBENs7vaw',
    appId: '1:583000002076:ios:3037a0977c993aeb1f19d9',
    messagingSenderId: '583000002076',
    projectId: 'travel-together-d671c',
    storageBucket: 'travel-together-d671c.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
}
